"""empty message

Revision ID: 02185c08b1a5
Revises: ef7b50cb998b
Create Date: 2019-01-27 11:40:49.807248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "02185c08b1a5"
down_revision = "ef7b50cb998b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product_variants", sa.Column("upcharge", sa.Float(), nullable=True))
    op.drop_column("product_variants", "vendor_cost_oversize")
    op.drop_column("product_variants", "margin_oversize")
    op.drop_column("product_variants", "upcharges")
    op.drop_column("product_variants", "vendor_cost_oversize_list")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_variants",
        sa.Column(
            "vendor_cost_oversize_list",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "product_variants",
        sa.Column(
            "upcharges", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "product_variants",
        sa.Column(
            "margin_oversize",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "product_variants",
        sa.Column(
            "vendor_cost_oversize",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("product_variants", "upcharge")
    # ### end Alembic commands ###
