"""empty message

Revision ID: 03e22d8eac05
Revises: 2dfad2b0a3cd
Create Date: 2019-08-19 14:50:24.477090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "03e22d8eac05"
down_revision = "2dfad2b0a3cd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_campaigns",
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("campaign_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"],),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"],),
    )
    op.drop_table("accounts_campaigns")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts_campaigns",
        sa.Column("account_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("campaign_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name="accounts_campaigns_account_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"], ["campaigns.id"], name="accounts_campaigns_campaign_id_fkey"
        ),
        sa.PrimaryKeyConstraint("account_id", "campaign_id", name="accounts_campaigns_pkey"),
    )
    op.drop_table("account_campaigns")
    # ### end Alembic commands ###
