"""Track product_id in CampaignProductVariant

Revision ID: 17daabcf3aaa
Revises: c78fe7219979
Create Date: 2020-02-24 20:33:02.041583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "17daabcf3aaa"
down_revision = "c78fe7219979"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("campaign_product_variants", sa.Column("product_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("campaign_product_variants", "product_id")
    # ### end Alembic commands ###
