"""empty message

Revision ID: 18f0c3037736
Revises: 4ddbecf06868
Create Date: 2019-12-04 13:58:36.302973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "18f0c3037736"
down_revision = "4ddbecf06868"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("campaigns", sa.Column("distributor_po", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("campaigns", "distributor_po")
    # ### end Alembic commands ###
