"""empty message

Revision ID: 23c23b3aeb48
Revises: 216f1c49cfe4
Create Date: 2019-02-07 12:56:53.061850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "23c23b3aeb48"
down_revision = "216f1c49cfe4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("resources_hash_key", "resources", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("resources_hash_key", "resources", ["hash"])
    # ### end Alembic commands ###
