"""empty message

Revision ID: 23dce09534a3
Revises: fd967b2645d6
Create Date: 2020-01-29 14:30:16.366927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "23dce09534a3"
down_revision = "fd967b2645d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product_variants", sa.Column("is_default", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_variants", "is_default")
    # ### end Alembic commands ###
