"""empty message

Revision ID: 2663146645e3
Revises: d4a20318755c
Create Date: 2019-11-12 14:07:18.099895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2663146645e3"
down_revision = "d4a20318755c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("campaigns", sa.Column("complete", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("campaigns", "complete")
    # ### end Alembic commands ###
