"""Drop unused email_campaign column

Revision ID: 2993c317aeba
Revises: a96e9d7dcd0e
Create Date: 2020-02-23 01:12:31.627669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2993c317aeba"
down_revision = "a96e9d7dcd0e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("campaigns", "email_campaign")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "campaigns", sa.Column("email_campaign", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
