"""empty message

Revision ID: 2b0fac1c8703
Revises: 67fc4eea77eb
Create Date: 2018-12-20 13:17:14.669376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2b0fac1c8703"
down_revision = "67fc4eea77eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product_variants", sa.Column("decorations", sa.JSON(), nullable=True))
    op.add_column("product_variants", sa.Column("description", sa.String(), nullable=True))
    op.add_column("product_variants", sa.Column("upcharges", sa.JSON(), nullable=True))
    op.add_column("product_variants", sa.Column("vendor_cost", sa.Float(), nullable=True))
    op.add_column(
        "product_variants",
        sa.Column("vendor_cost_oversize_list", sa.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "product_variants", sa.Column("vendor_cost_oversize_price", sa.Float(), nullable=True)
    )
    op.add_column("product_variants", sa.Column("vendor_item_number", sa.String(), nullable=True))
    op.add_column("product_variants", sa.Column("vendor_name", sa.String(), nullable=True))
    op.drop_column("product_variants", "price")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_variants",
        sa.Column(
            "price", postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("product_variants", "vendor_name")
    op.drop_column("product_variants", "vendor_item_number")
    op.drop_column("product_variants", "vendor_cost_oversize_price")
    op.drop_column("product_variants", "vendor_cost_oversize_list")
    op.drop_column("product_variants", "vendor_cost")
    op.drop_column("product_variants", "upcharges")
    op.drop_column("product_variants", "description")
    op.drop_column("product_variants", "decorations")
    # ### end Alembic commands ###
