"""empty message

Revision ID: 2b2dfc850dc8
Revises: 44feabda7bf2
Create Date: 2019-11-25 15:49:45.706790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2b2dfc850dc8"
down_revision = "44feabda7bf2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("campaigns", "start_date_t")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "campaigns",
        sa.Column(
            "start_date_t", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
