"""empty message

Revision ID: 36c58f2eab13
Revises: 9125961a6531
Create Date: 2019-07-01 13:56:47.008854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "36c58f2eab13"
down_revision = "9125961a6531"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("campaigns", sa.Column("bfl_cost", sa.Float(), nullable=True))
    op.drop_column("product_variants", "bag_fold_label_cost")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_variants",
        sa.Column(
            "bag_fold_label_cost",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("campaigns", "bfl_cost")
    # ### end Alembic commands ###
