"""empty message

Revision ID: 381df0c07b52
Revises: 569894ef5b09
Create Date: 2019-10-08 08:10:07.909425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "381df0c07b52"
down_revision = "569894ef5b09"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "vendors", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vendors", type_="unique")
    # ### end Alembic commands ###
