"""empty message

Revision ID: 40b96efa37e3
Revises: 
Create Date: 2018-12-10 15:16:18.716588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "40b96efa37e3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "distributors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "resources",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("hash", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.Column("linked_to", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("hash"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "campaigns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("company_name", sa.String(), nullable=True),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("storefront_pricing", sa.Boolean(), nullable=True),
        sa.Column("company_allowance", sa.Float(), nullable=True),
        sa.Column("company_allowance_personal_pay", sa.String(), nullable=True),
        sa.Column("items_count_limit", sa.Integer(), nullable=True),
        sa.Column("price_limit", sa.Float(), nullable=True),
        sa.Column("email_shoppers", sa.Boolean(), nullable=True),
        sa.Column("email_campaign", sa.Boolean(), nullable=True),
        sa.Column("checkout_fields", sa.JSON(), nullable=True),
        sa.Column("distributor_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["distributor_id"], ["distributors.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "product_attributes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("values", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("distributor_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["distributor_id"], ["distributors.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("distributor_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["distributor_id"], ["distributors.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("distributor_id", sa.Integer(), nullable=True),
        sa.Column("campaign_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"],),
        sa.ForeignKeyConstraint(["distributor_id"], ["distributors.id"],),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("campaign_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nickname", sa.String(), nullable=True),
        sa.Column("company_name", sa.String(), nullable=True),
        sa.Column("street_and_number", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("zip_code", sa.String(), nullable=True),
        sa.Column("delivery_contact", sa.String(), nullable=True),
        sa.Column("suite_unit_etc", sa.String(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("campaign_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_attribute_types",
        sa.Column("attr_id", sa.Integer(), nullable=True),
        sa.Column("type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["attr_id"], ["product_attributes.id"],),
        sa.ForeignKeyConstraint(["type_id"], ["product_types.id"],),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("product_type_id", sa.Integer(), nullable=True),
        sa.Column("distributor_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["distributor_id"], ["distributors.id"],),
        sa.ForeignKeyConstraint(["product_type_id"], ["product_types.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("campaign_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"],),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_variants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("sku", sa.String(), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("campaign_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"],),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=True),
        sa.Column("token_type", sa.String(), nullable=True),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("product_variant_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"],),
        sa.ForeignKeyConstraint(["product_variant_id"], ["product_variants.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"],),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_notes")
    op.drop_table("order_items")
    op.drop_table("order_events")
    op.drop_table("tokens")
    op.drop_table("product_variants")
    op.drop_table("orders")
    op.drop_table("products")
    op.drop_table("product_attribute_types")
    op.drop_table("locations")
    op.drop_table("departments")
    op.drop_table("accounts")
    op.drop_table("product_types")
    op.drop_table("product_attributes")
    op.drop_table("campaigns")
    op.drop_table("roles")
    op.drop_table("resources")
    op.drop_table("distributors")
    # ### end Alembic commands ###
