"""empty message

Revision ID: 412dd8dcf954
Revises: 525ce8483dc4
Create Date: 2018-12-27 10:25:10.106738

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "412dd8dcf954"
down_revision = "525ce8483dc4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product_variants", sa.Column("vendor_cost_oversize", sa.Float(), nullable=True))
    op.drop_column("product_variants", "vendor_cost_oversize_cost")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_variants",
        sa.Column(
            "vendor_cost_oversize_cost",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("product_variants", "vendor_cost_oversize")
    # ### end Alembic commands ###
