"""empty message

Revision ID: 43c6d59ac360
Revises: baa5acadfafa
Create Date: 2020-01-10 17:40:43.550405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "43c6d59ac360"
down_revision = "baa5acadfafa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_attributes", sa.Column("allowDistributorsAddValues", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "product_attributes", sa.Column("allowSalesAddValues", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "product_attributes",
        sa.Column("associateWith", sa.ARRAY(sa.Integer), nullable=True, server_default="{}"),
    )
    op.add_column("product_attributes", sa.Column("displayAs", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_attributes", "displayAs")
    op.drop_column("product_attributes", "associateWith")
    op.drop_column("product_attributes", "allowSalesAddValues")
    op.drop_column("product_attributes", "allowDistributorsAddValues")
    # ### end Alembic commands ###
