"""empty message

Revision ID: 44feabda7bf2
Revises: a547a1dd1818
Create Date: 2019-11-25 15:29:38.920658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "44feabda7bf2"
down_revision = "a547a1dd1818"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("campaigns", sa.Column("start_date_t", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("campaigns", "start_date_t")
    # ### end Alembic commands ###
