"""empty message

Revision ID: 47ee3533296a
Revises: 23c23b3aeb48
Create Date: 2019-02-28 22:33:48.420477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "47ee3533296a"
down_revision = "23c23b3aeb48"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("reports_enabled", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "reports_enabled")
    # ### end Alembic commands ###
