"""empty message

Revision ID: 4a2b95d61a83
Revises: ae1cda3aa76b
Create Date: 2020-01-15 13:41:22.758584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4a2b95d61a83"
down_revision = "ae1cda3aa76b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("distributors", sa.Column("address", sa.String(), nullable=True))
    op.add_column("distributors", sa.Column("email", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("distributors", "email")
    op.drop_column("distributors", "address")
    # ### end Alembic commands ###
