"""empty message

Revision ID: 569894ef5b09
Revises: fe13f0673e0b
Create Date: 2019-10-07 10:39:17.684161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "569894ef5b09"
down_revision = "fe13f0673e0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vendors", sa.Column("address", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vendors", "address")
    # ### end Alembic commands ###
