"""Drop unused RmProductAttributesValues model 

Revision ID: 572e0dd8600e
Revises: daf631021925
Create Date: 2020-02-21 12:59:07.086820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "572e0dd8600e"
down_revision = "daf631021925"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rm_product_attributes_values")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rm_product_attributes_values",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("account_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("product_attribute_value_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("distributor_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name="rm_product_attributes_values_account_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["distributor_id"],
            ["distributors.id"],
            name="rm_product_attributes_values_distributor_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["product_attribute_value_id"],
            ["product_attributes_values.id"],
            name="rm_product_attributes_values_product_attribute_value_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="rm_product_attributes_values_pkey"),
    )
    # ### end Alembic commands ###
