"""empty message

Revision ID: 59636c560a72
Revises: 40b96efa37e3
Create Date: 2018-12-11 11:18:56.169976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "59636c560a72"
down_revision = "40b96efa37e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("checkout_fields", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "checkout_fields")
    # ### end Alembic commands ###
