"""empty message

Revision ID: 60d39c0c6885
Revises: 02185c08b1a5
Create Date: 2019-01-28 11:20:42.516419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "60d39c0c6885"
down_revision = "02185c08b1a5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("campaigns", sa.Column("message", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("campaigns", "message")
    # ### end Alembic commands ###
