"""empty message

Revision ID: 67fc4eea77eb
Revises: 669a066aa7cc
Create Date: 2018-12-17 16:58:51.944972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "67fc4eea77eb"
down_revision = "669a066aa7cc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("campaigns", sa.Column("created_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("campaigns", "created_at")
    # ### end Alembic commands ###
