"""empty message

Revision ID: 7095bd817b5b
Revises: a829ccbf827a
Create Date: 2018-12-12 14:03:21.035834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7095bd817b5b"
down_revision = "a829ccbf827a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product_variants", sa.Column("price", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_variants", "price")
    # ### end Alembic commands ###
