"""empty message

Revision ID: 70b51e30478b
Revises: 93c4ae5b3744
Create Date: 2019-01-17 12:25:58.660604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "70b51e30478b"
down_revision = "93c4ae5b3744"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("basket", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "basket")
    # ### end Alembic commands ###
