"""empty message

Revision ID: 77b04919a2c8
Revises: 18f0c3037736
Create Date: 2020-01-03 17:02:11.981181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "77b04919a2c8"
down_revision = "18f0c3037736"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_attributes_values",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("product_attribute_id", sa.Integer(), nullable=True),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"],),
        sa.ForeignKeyConstraint(["product_attribute_id"], ["product_attributes.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "related_product_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("product_type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"],),
        sa.ForeignKeyConstraint(["product_type_id"], ["product_types.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rm_product_attributes_values",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("product_attribute_value_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"],),
        sa.ForeignKeyConstraint(["product_attribute_value_id"], ["product_attributes_values.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("product_attribute_types")
    op.add_column("product_attributes", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("product_attributes", sa.Column("product_type_id", sa.Integer(), nullable=True))
    op.add_column("product_attributes", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.drop_constraint(
        "product_attributes_distributor_id_fkey", "product_attributes", type_="foreignkey"
    )
    op.create_foreign_key(None, "product_attributes", "product_types", ["product_type_id"], ["id"])
    op.drop_column("product_attributes", "distributor_id")
    op.drop_column("product_attributes", "values")
    op.add_column("product_types", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("product_types", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.drop_constraint("product_types_distributor_id_fkey", "product_types", type_="foreignkey")
    op.drop_column("product_types", "distributor_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_types",
        sa.Column("distributor_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "product_types_distributor_id_fkey",
        "product_types",
        "distributors",
        ["distributor_id"],
        ["id"],
    )
    op.drop_column("product_types", "updated_at")
    op.drop_column("product_types", "created_at")
    op.add_column(
        "product_attributes",
        sa.Column("values", postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    )
    op.add_column(
        "product_attributes",
        sa.Column("distributor_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "product_attributes", type_="foreignkey")
    op.create_foreign_key(
        "product_attributes_distributor_id_fkey",
        "product_attributes",
        "distributors",
        ["distributor_id"],
        ["id"],
    )
    op.drop_column("product_attributes", "updated_at")
    op.drop_column("product_attributes", "product_type_id")
    op.drop_column("product_attributes", "created_at")
    op.create_table(
        "product_attribute_types",
        sa.Column("attr_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("type_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["attr_id"], ["product_attributes.id"], name="product_attribute_types_attr_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["type_id"], ["product_types.id"], name="product_attribute_types_type_id_fkey"
        ),
    )
    op.drop_table("rm_product_attributes_values")
    op.drop_table("related_product_types")
    op.drop_table("product_attributes_values")
    # ### end Alembic commands ###
