"""empty message

Revision ID: 90cc6a5eb173
Revises: d80aaadae6a7
Create Date: 2019-10-16 15:24:53.998689

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = "90cc6a5eb173"
down_revision = "d80aaadae6a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "distributors",
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default="now()"),
    )
    op.add_column(
        "distributors",
        sa.Column("modified_at", sa.DateTime(), nullable=False, server_default="now()"),
    )
    op.add_column(
        "distributors",
        sa.Column("is_deleted", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column(
        "product_types",
        sa.Column("is_deleted", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column(
        "products", sa.Column("is_deleted", sa.Boolean(), nullable=False, server_default="false")
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("distributors", "modified_at")
    op.drop_column("distributors", "created_at")
    op.drop_column("distributors", "is_deleted")
    op.drop_column("product_types", "is_deleted")
    op.drop_column("products", "is_deleted")
    # ### end Alembic commands ###
