"""empty message

Revision ID: 9125961a6531
Revises: c1826a971b7b
Create Date: 2019-06-12 12:47:02.324736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9125961a6531"
down_revision = "c1826a971b7b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("campaigns", sa.Column("created_by", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("campaigns", "created_by")
    # ### end Alembic commands ###
