"""empty message

Revision ID: 93c4ae5b3744
Revises: 8f9a35f1728e
Create Date: 2019-01-16 15:36:11.145191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "93c4ae5b3744"
down_revision = "8f9a35f1728e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_variants", "name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_variants", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
