"""empty message

Revision ID: 97d657f8cad4
Revises: 60d39c0c6885
Create Date: 2019-01-31 12:09:09.295547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "97d657f8cad4"
down_revision = "60d39c0c6885"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_variants", "vendor_item_number")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_variants",
        sa.Column("vendor_item_number", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
