"""empty message

Revision ID: a829ccbf827a
Revises: dca683056c34
Create Date: 2018-12-12 11:28:15.826486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a829ccbf827a"
down_revision = "dca683056c34"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("campaigns", sa.Column("email_shopper", sa.Boolean(), nullable=True))
    op.drop_column("campaigns", "email_shoppers")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "campaigns", sa.Column("email_shoppers", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.drop_column("campaigns", "email_shopper")
    # ### end Alembic commands ###
