"""empty message

Revision ID: a85ec3c2aaac
Revises: 43c6d59ac360
Create Date: 2020-01-14 11:45:50.670810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a85ec3c2aaac"
down_revision = "43c6d59ac360"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("distributors", sa.Column("campaign_cost", sa.Float(), nullable=True))
    op.add_column("distributors", sa.Column("max_sales_count", sa.Integer(), nullable=True))
    op.add_column("distributors", sa.Column("transaction_cost", sa.Float(), nullable=True))
    op.add_column(
        "product_attributes_values", sa.Column("distributor_id", sa.Integer(), nullable=True)
    )
    op.add_column("product_attributes_values", sa.Column("position", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "product_attributes_values", "distributors", ["distributor_id"], ["id"]
    )
    op.add_column(
        "rm_product_attributes_values", sa.Column("distributor_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "rm_product_attributes_values", "distributors", ["distributor_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rm_product_attributes_values", type_="foreignkey")
    op.drop_column("rm_product_attributes_values", "distributor_id")
    op.drop_constraint(None, "product_attributes_values", type_="foreignkey")
    op.drop_column("product_attributes_values", "position")
    op.drop_column("product_attributes_values", "distributor_id")
    op.drop_column("distributors", "transaction_cost")
    op.drop_column("distributors", "max_sales_count")
    op.drop_column("distributors", "campaign_cost")
    # ### end Alembic commands ###
