"""empty message

Revision ID: d80aaadae6a7
Revises: 569894ef5b09
Create Date: 2019-10-11 11:11:54.652215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d80aaadae6a7"
down_revision = "569894ef5b09"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("order_items", "product_variant_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("order_items", "product_variant_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
