"""Drop DataResource model

Revision ID: d8faec4baa2b
Revises: 692020fc477f
Create Date: 2020-02-19 11:47:05.077544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d8faec4baa2b"
down_revision = "692020fc477f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resources")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resources",
        sa.Column("uuid", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("hash", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "meta", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("linked_to", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("uuid", name="resources_pkey"),
    )
    # ### end Alembic commands ###
