"""Refactor columns on ProductAttribute

Revision ID: daf631021925
Revises: e796a58bdc99
Create Date: 2020-02-19 20:28:56.774411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "daf631021925"
down_revision = "e796a58bdc99"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product_attributes", sa.Column("assoc_added_costs", sa.Boolean(), nullable=True))
    op.add_column("product_attributes", sa.Column("assoc_bin_id", sa.Boolean(), nullable=True))
    op.add_column(
        "product_attributes", sa.Column("assoc_product_image", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "product_attributes", sa.Column("distributors_enabled", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "product_attributes", sa.Column("sales_execs_enabled", sa.Boolean(), nullable=True)
    )
    op.drop_column("product_attributes", "allowDistributorsAddValues")
    op.drop_column("product_attributes", "displayAs")
    op.drop_column("product_attributes", "associateWith")
    op.drop_column("product_attributes", "allowSalesAddValues")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_attributes",
        sa.Column("allowSalesAddValues", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "product_attributes",
        sa.Column(
            "associateWith",
            postgresql.ARRAY(sa.INTEGER()),
            server_default=sa.text("'{}'::integer[]"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "product_attributes",
        sa.Column("displayAs", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "product_attributes",
        sa.Column("allowDistributorsAddValues", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_column("product_attributes", "sales_execs_enabled")
    op.drop_column("product_attributes", "distributors_enabled")
    op.drop_column("product_attributes", "assoc_product_image")
    op.drop_column("product_attributes", "assoc_bin_id")
    op.drop_column("product_attributes", "assoc_added_costs")
    # ### end Alembic commands ###
