"""empty message

Revision ID: dca683056c34
Revises: 59636c560a72
Create Date: 2018-12-12 10:48:26.534268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dca683056c34"
down_revision = "59636c560a72"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("campaigns", sa.Column("status", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("campaigns", "status")
    # ### end Alembic commands ###
