"""empty message

Revision ID: df7abe53b7e6
Revises: 4a2b95d61a83
Create Date: 2020-01-16 13:06:21.949172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "df7abe53b7e6"
down_revision = "4a2b95d61a83"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vendors", sa.Column("is_pick_pack", sa.Boolean(), nullable=True))
    op.add_column("vendors", sa.Column("is_supplier", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vendors", "is_supplier")
    op.drop_column("vendors", "is_pick_pack")
    # ### end Alembic commands ###
