"""empty message

Revision ID: e7324ba31474
Revises: 03e22d8eac05
Create Date: 2019-09-17 13:35:21.147935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e7324ba31474"
down_revision = "03e22d8eac05"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("campaigns", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("campaigns", "updated_at")
    # ### end Alembic commands ###
