"""empty message

Revision ID: ee6f54349227
Revises: 77ddc391c19d
Create Date: 2020-01-23 16:33:17.863090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ee6f54349227"
down_revision = "77ddc391c19d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "related_product_types_product_type_id_fkey", "related_product_types", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "related_product_types", "product_types", ["product_type_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "related_product_types", type_="foreignkey")
    op.create_foreign_key(
        "related_product_types_product_type_id_fkey",
        "related_product_types",
        "product_types",
        ["product_type_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
