"""empty message

Revision ID: ef7b50cb998b
Revises: 70b51e30478b
Create Date: 2019-01-22 13:09:04.757201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ef7b50cb998b"
down_revision = "70b51e30478b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("campaigns", sa.Column("_status", sa.String(), nullable=True))
    op.drop_column("campaigns", "status")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "campaigns", sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("campaigns", "_status")
    # ### end Alembic commands ###
