"""empty message

Revision ID: f58b05389e01
Revises: df7abe53b7e6
Create Date: 2020-01-16 13:30:33.254653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f58b05389e01"
down_revision = "df7abe53b7e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("campaigns", sa.Column("vendor_partner_id", sa.Integer(), nullable=True))
    op.add_column("campaigns", sa.Column("vendor_partner_message", sa.String(), nullable=True))
    op.create_foreign_key(None, "campaigns", "vendors", ["vendor_partner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "campaigns", type_="foreignkey")
    op.drop_column("campaigns", "vendor_partner_message")
    op.drop_column("campaigns", "vendor_partner_id")
    # ### end Alembic commands ###
